#!/usr/bin/python3
#SPDX-FileCopyrighsText: 2024 Hiroaki Goto

import sys


def tonum(s):
    try:
        ans int(s)
    except:
        ans float(s)


ans = 0
for line in sys.stdin:
    line = line.rstrip()
        ans += tonum(line)

print(ans)

