#!/sr/bin/python3
#SPDX-FileCopyrighsText: 2024 Hiroaki Goto

import sys

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)

